name: 'TPM Agent'
description: 'A reusable GitHub Action for TPM-related operations using Semantic Kernel'
author: 'Matt Dotson'

inputs:
  operation:
    description: 'The operation to perform'
    required: true
    default: 'info'
  target:
    description: 'Target for the operation'
    required: false
    default: ''
  verbose:
    description: 'Enable verbose output'
    required: false
    default: 'false'

outputs:
  result:
    description: 'Result of the operation'
  status:
    description: 'Status of the operation'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'shield'
  color: 'blue'