name: Test TPM Agent Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test TPM Agent Action
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test Info Operation
        uses: ./
        with:
          operation: 'info'
          verbose: 'true'
        id: test-info
      
      - name: Test Check Operation
        uses: ./
        with:
          operation: 'check'
          target: 'system'
        id: test-check
      
      - name: Test Validate Operation
        uses: ./
        with:
          operation: 'validate'
          verbose: 'true'
        id: test-validate
      
      - name: Verify Results
        run: |
          echo "Info Operation Results:"
          echo "  Status: ${{ steps.test-info.outputs.status }}"
          echo "  Result: ${{ steps.test-info.outputs.result }}"
          echo ""
          echo "Check Operation Results:"
          echo "  Status: ${{ steps.test-check.outputs.status }}"
          echo "  Result: ${{ steps.test-check.outputs.result }}"
          echo ""
          echo "Validate Operation Results:"
          echo "  Status: ${{ steps.test-validate.outputs.status }}"
          echo "  Result: ${{ steps.test-validate.outputs.result }}"
          
          # Verify all operations succeeded
          if [ "${{ steps.test-info.outputs.status }}" != "success" ] || \
             [ "${{ steps.test-check.outputs.status }}" != "success" ] || \
             [ "${{ steps.test-validate.outputs.status }}" != "success" ]; then
            echo "❌ Some operations failed!"
            exit 1
          else
            echo "✅ All operations completed successfully!"
          fi
      
      - name: Test Error Handling
        uses: ./
        with:
          operation: 'invalid'
        continue-on-error: true
        id: test-error
      
      - name: Verify Error Handling
        run: |
          echo "Error Test Results:"
          echo "  Status: ${{ steps.test-error.outputs.status }}"
          echo "  Result: ${{ steps.test-error.outputs.result }}"
          
          if [ "${{ steps.test-error.outputs.status }}" == "error" ]; then
            echo "✅ Error handling works correctly!"
          else
            echo "❌ Error handling failed!"
            exit 1
          fi