name: Validate Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Action Configuration
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Validate action.yml
        run: |
          echo "Validating action.yml structure..."
          
          # Check if action.yml exists
          if [ ! -f "action.yml" ]; then
            echo "❌ action.yml not found!"
            exit 1
          fi
          
          # Check required fields
          if ! grep -q "name:" action.yml; then
            echo "❌ Missing 'name' field in action.yml"
            exit 1
          fi
          
          if ! grep -q "description:" action.yml; then
            echo "❌ Missing 'description' field in action.yml"
            exit 1
          fi
          
          if ! grep -q "runs:" action.yml; then
            echo "❌ Missing 'runs' field in action.yml"
            exit 1
          fi
          
          echo "✅ action.yml structure is valid!"
      
      - name: Validate README
        run: |
          echo "Validating README.md..."
          
          # Check if README exists
          if [ ! -f "README.md" ]; then
            echo "❌ README.md not found!"
            exit 1
          fi
          
          # Check for usage examples
          if ! grep -q "## Usage" README.md; then
            echo "❌ Missing usage section in README.md"
            exit 1
          fi
          
          if ! grep -q "uses: mattdot/tpmagent" README.md; then
            echo "❌ Missing usage example in README.md"
            exit 1
          fi
          
          echo "✅ README.md is valid!"
      
      - name: Validate License
        run: |
          echo "Validating LICENSE..."
          
          if [ ! -f "LICENSE" ]; then
            echo "❌ LICENSE file not found!"
            exit 1
          fi
          
          if ! grep -q "MIT License" LICENSE; then
            echo "❌ License type not clearly specified"
            exit 1
          fi
          
          echo "✅ LICENSE is valid!"
      
      - name: Check for required workflows
        run: |
          echo "Checking for test workflows..."
          
          if [ ! -d ".github/workflows" ]; then
            echo "❌ .github/workflows directory not found!"
            exit 1
          fi
          
          if [ ! -f ".github/workflows/test-action.yml" ]; then
            echo "❌ Test workflow not found!"
            exit 1
          fi
          
          echo "✅ Workflow structure is valid!"
      
      - name: Summary
        run: |
          echo "🎉 All validations passed! The repository is ready to be used as a GitHub Action."
          echo ""
          echo "To use this action in other repositories:"
          echo "  uses: mattdot/tpmagent@v1"
          echo ""
          echo "Next steps:"
          echo "1. Create a release (v1) to make the action available"
          echo "2. Add any additional functionality as needed"
          echo "3. Update documentation based on actual use cases"